---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-ha-workshop-west
  region: us-west-1
nodeGroups:
  - name: aws-workshop-ng
    instanceType: m5.large
    desiredCapacity: 2